### ISSUE TITLE
Multi-line lists are not indented or aligned

### ISSUE THREAD

**Issue by elementx54** [elementx54/moosefw_vim#10]
MOOSE input often has lists that span multiple lines. Currently the plugin does not do anything with these lines so it ends up looking like this:
```
subdomain = '1 1 1 1
1 1 1 1
1 1 1 1'
```
It would look much better if it was aligned with the ' or ":
```
subdomain = '1 1 1 1
             1 1 1 1
             1 1 1 1'
```
The plugin currently does nothing and so the next line lines up with "subdomain" either while typing or when using the re-tab `=` command.  

Thanks to @bwspenc for bringing this to my attention.

**Comment by bwspenc** [comment]
Nice! I just tested it, and it works beautifully!
