### ISSUE TITLE
Indenting wrong for lines with comments

### ISSUE THREAD

**Issue by bwspenc** [elementx54/moosefw_vim#11]
OK, I noticed another small issue with the indenting plugin:

If I am commenting out blocks of code, I usually put a comment character on the first column of the commented out lines, and like the commented-out code to look like this:

```
[TopLevel]
#  foo = foo
[]

#[TopLevel1]
#  [nested]
#    foo = foo
#  []
#[]
```

However, the indenting plugin indents them as if they are not commented out:
```
[TopLevel]
  #  foo = foo
[]

#[TopLevel1]
  #  [nested]
    #    foo = foo
  #  []
#[]
```

Not only does this look ugly (in my opinion), but it makes it hard to uncomment large commented-out blocks.

I guess the way I would expect this to behave is that if the comment is in the first column of a line, its indenting should be left alone, but if it is in another position, I would want it indented with the code, such as this example:
```
[TopLevel]
  #I'm setting foo to a foo because it's a foo
  foo = foo
[]
```
Not sure if that's too hard to do.

**Comment by elementx54** [comment]
That is ugly. I'll see what I can do. I'm thinking the best option is to just ignore lines with comments as the user *probably* puts the comments where the user wants them. 😉   

And as a shameless plug: this plugin has a commenting and un-commenting feature that works in both visual and normal mode. Below is the part of the help document about it.
```
*moose_fw-commenting*

MOOSE inputs allow for comments. A common practice when debugging an input
file is to "comment out" part of the input file and rerun the input file. To
aid with this work flow, typing [count]<Leader>c|C converts the lines to
comments and typing [count]<Leader>x|X removes the comment conversion. Lower
case moves down the buffer, while upper case moves up the buffer. An effort is
made to preserve indentation and previous|after comment indentation when in
normal mode. Visual mode may or may not preserve comment indentation, but
remains in visual mode after commenting is complete
```

And would you look at that! 👀 It is missing a period at the very end. Opening an issue for that now. 😛

**Comment by elementx54** [comment]
@bwspenc 
I found that as I tried to have it just ignore the comments starting in the first column that if you decided to comment out a sub-block you'd end up with this:
```
[top]
  #[subout]
  #  type = test
  #  value = foo
  #  [nest]
  #    type = nest
  #    value = bar
  #  []
  #[]
[]

:gg=G

[top]
  #[subout]
    #  type = test
    #  value = foo
    #  [nest]
      #    type = nest
      #    value = bar
    #  []
  #[]
[]
```
I think that is also *ugly*. So, my fix is to just trust the user that they put the comment where they want it. The commenting feature of the plugin should work great now and fixing the indent with `=` shouldn't touch it.  

Let me know if this works for you.

**Comment by bwspenc** [comment]
I finally got a chance to test this.  It works great. Thanks!
