### ISSUE TITLE
Syntax detection

### ISSUE THREAD

**Issue by taoyiliang** [elementx54/moosefw_vim#4]
When writing a python script I often trigger the syntax detection erroneously.

For instance, I have the following (in the first 50 lines of the file):
```python
cases = ['Coated','Uncoated']

solns = []
for i in range(6):
  ...
```

Because the syntax found [stuff] followed by [], it triggers as GetPot instead of Python.

I can work around this by excluding moosefw checking on certain file extensions, but a more general solution would be great.

**Comment by elementx54** [comment]
Your example actually doesn't create a false filetype detection, but I agree that the detection could be more strict. As such, the filetype detection will now only classify the filetype when the top block starts at the start-of-the-line *and* ends at the start-of-the-line.  

I'm going to leave this open since your example didn't actually create the false detection. @taoyiliang Does the new commit still cause a false detection with your python script?

**Comment by taoyiliang** [comment]
Here's an example file that (before your fix) failed the syntax.  I haven't had a chance to check against your fix yet.

```python
import os
import sys

rDir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
testDir = os.path.join(rDir,'tests')

def getRegressionTests(skipThese=[],skipExpectedFails=True):
  """
    @ In, skipThese, list(str), filenames to skip in check
    @ In, skipExpectedFails, bool, if True skips framework/ErrorCheck directory
    @ Out, dict, dict[dir] = list(filenames)
  """
  testsFilenames = []
  #search for all the 'tests' files
  for root, dirs, files in os.walk(testDir):
    if skipExpectedFails and 'ErrorChecks' in root.split(os.sep):
      continue
    if 'tests' in files:
      testsFilenames.append((root,os.path.join(root, 'tests')))
  #read all "input" node files from "tests" files
  doTests = {}
  for root,testFilename in testsFilenames:
    testsFile = file(testFilename,'r')
    for line in testsFile:
      if line.strip().startswith('input'):
        newtest = line.split('=')[1].strip().strip("'")
        if newtest not in skipThese and newtest.endswith('.xml'):
          if root not in doTests.keys(): doTests[root]=[]
          doTests[root].append(newtest)
  return doTests
```

**Comment by elementx54** [comment]
Found the lines that were triggering the false filetype detection:
```
    @ Out, dict, dict[dir] = list(filenames)
  """
  testsFilenames = []
```

The new commit fixes the false detection.
