### ISSUE TITLE
Support New MOOSE Input Syntax

### ISSUE THREAD

**Issue by elementx54** [elementx54/moosefw_vim#8]
@bwspenc stopped by and asked for the upgrade to supporting the new moose input syntax. So I'm opening this for him so I don't forget ... cause I probably would.

Basically, the input can now have a mix of what I call "top" blocks and "sub" blocks in the file. Sub blocks still cannot be top level blocks.

```
[TopOne]
  [new_format]
    [./mixed_too]
      tabs = correct
    [../]
  []
[]
```

The plugin should be able to highlight, fold, and tab the new syntax. Technically, MOOSE itself does not require any of those, but the plugin does to help the user (you) to write the file correctly the first time and make it look pretty and navigable when you're done.

**Comment by PaulTalbot-INL** [comment]
👍
