### ISSUE TITLE
Support Cascades in Top Openers

### ISSUE THREAD

**Issue by elementx54** [elementx54/moosefw_vim#9]
I just found out that MOOSE is able to handle cascades in "top" openers. I'm not sure if it can do it in "sub" blocks, but I see no reason why it shouldn't. Basically, MOOSE thinks these blocks are the same.
```
[Top/Next/third]
  [./all]
    type = issue
  [../]
[]

[Top]
  [Next]
    [third]
      [./all]
        type = issue
      [../]
    []
  []
[]
```

A nice short hand way to not go nest *cazy* in the input file. Note that I am also showing the new MOOSE syntax mixed with old "sub" blocks, though all could be the old style. The fix to the plugin would at least need to be able to fold and tab the Cascade correctly. I'm not sure how to handle the highlighting though. Currently, only `[Top]` would be highlighted. I might just have the rest of the line inherit the highlighting from `[Top]`. Not sure on that one, yet.  

I will also make it handle "sub" block cascades.
```
[Top]
  [Next/third/all]
    type = issue
  []
[]
```

**Comment by bwspenc** [comment]
Awesome!  I'll give it a try.
